export enum Status {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  INACTIVE = 'INACTIVE',
  OVERDUE = 'OVERDUE',
  PREDICTED = 'PREDICTED',
}
